BEGIN
  EXECUTE IMMEDIATE 'DROP USER citysphere CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE USER citysphere
  IDENTIFIED BY citysphere123
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;
GRANT ALL PRIVILEGES TO citysphere; 